version: "3.9"

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright

    image: playwright-framework

    container_name: playwright-runner

    command: sh run-tests.sh

    volumes:
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results
      - ./test-results:/app/test-results
      - .:/app