name: Reusable Playwright Workflow

on:
  workflow_call:
    inputs:
        command:
          required: true
          type: string
        browser:
          required: true
          type: string

jobs:
  playwright:
    name: Playwright Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps ${{ inputs.browser }}

      - name: Run Playwright tests
        run: yarn ${{ inputs.command }} --project=${{  inputs.browser }}

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.browser }}-report
          path: playwright-report
          retention-days: 7