name: Smoke Github-Hosted CI with Matrix

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    
permissions:
  contents: write
  actions: read

jobs:
  smoke:
    name: ${{ matrix.project }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: Desktop Chromium
            engine: chromium
            credential_index: 0

          - project: Desktop Firefox
            engine: firefox
            credential_index: 1

          - project: Desktop WebKit
            engine: webkit
            credential_index: 2

          - project: Mobile Safari
            engine: webkit
            credential_index: 3

          - project: Mobile Chrome
            engine: chromium
            credential_index: 4

    uses: diepnguyen87/automation-workflows/.github/workflows/reusable-playwright-2.yml@v1.0.9
    with:
      suite: Smoke
      command: test:smoke
      browser: ${{ matrix.project }}
      engine: ${{ matrix.engine }}
      credential-index: ${{ matrix.credential_index }}
      image-tag: latest
      runner: ubuntu-latest

    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ENV_FILE_BASE64: ${{ secrets.ENV_FILE_BASE64 }}