name: Smoke Github-Hosted CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  smoke:
    name: ${{ matrix.project }}
    strategy:
      fail-fast: false
      matrix:
         include:
          - project: Desktop Chromium
            engine: chromium

          - project: Desktop Firefox
            engine: firefox

          - project: Desktop WebKit
            engine: webkit

          - project: Mobile Safari
            engine: webkit

          - project: Mobile Chrome
            engine: chromium

    uses: diepnguyen87/automation-workflows/.github/workflows/reusable-playwright-2.yml@v1.0.2
    with:
      suite: Smoke
      command: test:smoke
      browser: ${{ matrix.project }}
      engine: ${{ matrix.engine }}
      image-tag: latest
      runner: ubuntu-latest

    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
     