name: Smoke CI

on:
  push:
    branches:
      - day-31

  pull_request:
    branches:
      - day-31

jobs:
  smoke:
    name: Smoke Test - ${{ matrix.browser }}
    strategy:
      fail-fast: false
      matrix:
        browser:
        - Desktop Chromium
        - Desktop Firefox
        - Desktop WebKit
        - Mobile Safari
        - Mobile Chrome

    uses: ./.github/workflows/reusable-workflow.yml
    with:
      suite: Smoke
      command: test:smoke
      browser: ${{ matrix.browser }}

    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}