name: Playwright Smoke CI

on:
  push:
    branches:
      - day-31

  pull_request:
    branches:
      - day-31

jobs:
  smoke:
    name: Playwright Smoke Test
    uses: ./.github/workflows/reusable-playwright.yml
    with:
      command: test:smoke

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
