name: Smoke Github-Hosted CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  smoke:
    name: Smoke Test - ${{ matrix.project }}
    strategy:
      fail-fast: false
      matrix:
         include:
          - project: Desktop Chromium
            engine: chromium

          - project: Desktop Firefox
            engine: firefox

          - project: Desktop WebKit
            engine: webkit

          - project: Mobile Safari
            engine: webkit

          - project: Mobile Chrome
            engine: chromium

    uses: ./.github/workflows/reusable-workflow.yml
    with:
      suite: Smoke
      command: test:smoke
      browser: ${{ matrix.project }}
      engine: ${{ matrix.engine }}

    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}