name: Playwright Smoke CI

on:
  push:
    branches:
      - day-31

  pull_request:
    branches:
      - day-31

jobs:
  smoke:
    name: Playwright Smoke Test - ${{ matrix.browser }}
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    uses: ./.github/workflows/setup-playwright.yml
    with:
      command: test:smoke
      browser: ${{ matrix.browser }}